# Generated by Django 5.2.7 on 2025-10-31 05:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('festival', '0002_alter_artist_genres'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='location',
        ),
        migrations.RemoveField(
            model_name='performance',
            name='event',
        ),
        migrations.RemoveField(
            model_name='performance',
            name='performance_date',
        ),
        migrations.AddField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('FES', 'フェス'), ('TOUR', 'ツアー'), ('SOLO', '単独公演'), ('BATTLE', '対バン'), ('OTHER', 'その他')], default='FES', max_length=10),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='EventDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('venue', models.CharField(max_length=255)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='festival.event')),
            ],
        ),
        migrations.AddField(
            model_name='performance',
            name='event_day',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='festival.eventday'),
            preserve_default=False,
        ),
    ]
