# Generated by Django 5.2.7 on 2025-11-06 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('festival', '0003_remove_event_location_remove_performance_event_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='furigana',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
