# Generated by Django 5.2.7 on 2025-11-11 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('festival', '0004_artist_furigana'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artist',
            options={'ordering': ['furigana']},
        ),
        migrations.AddField(
            model_name='event',
            name='official_url',
            field=models.URLField(blank=True, null=True, verbose_name='公式サイトURL'),
        ),
    ]
