# Generated by Django 5.2.7 on 2025-11-13 00:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('festival', '0005_alter_artist_options_event_official_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relatedartist',
            name='artist',
        ),
        migrations.RemoveField(
            model_name='relatedartist',
            name='related_artist',
        ),
        migrations.RemoveField(
            model_name='performance',
            name='is_confirmed',
        ),
        migrations.AddField(
            model_name='artist',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='artist',
            name='twitter_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='performance',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='performance',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='eventday',
            unique_together={('event', 'date', 'venue')},
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='festival.event')),
            ],
        ),
        migrations.DeleteModel(
            name='ManualEntry',
        ),
        migrations.DeleteModel(
            name='RelatedArtist',
        ),
    ]
