# Generated by Django 5.2.7 on 2025-11-13 00:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('festival', '0006_remove_relatedartist_artist_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='performance',
            name='stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='festival.stage'),
        ),
    ]
