# Generated by Django 5.2.7 on 2025-11-13 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('festival', '0007_performance_stage'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='performance',
            unique_together={('event_day', 'artist')},
        ),
    ]
