# Generated by Django 5.2.7 on 2025-11-14 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('festival', '0008_alter_performance_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stage',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='stage',
            name='color_code',
            field=models.CharField(choices=[('#e3f2fd', '青系'), ('#fce4ec', 'ピンク系'), ('#e8f5e9', '緑系'), ('#fff3e0', 'オレンジ系'), ('#ede7f6', '紫系'), ('#f3e5f5', 'ラベンダー系'), ('#f9fbe7', 'ライム系'), ('#e0f7fa', 'シアン系'), ('#fbe9e7', 'サーモン系'), ('#f5f5f5', 'グレー系')], default='#e3f2fd', help_text='ステージカラー（タイムテーブル背景色）', max_length=7),
        ),
        migrations.AddField(
            model_name='stage',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='タイムテーブル上の表示順'),
        ),
    ]
