# Generated by Django 5.2.7 on 2025-11-21 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('festival', '0010_alter_stage_color_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stage',
            name='color_code',
            field=models.CharField(choices=[('#4A90E2', '青系'), ('#E9184E', 'ピンク系'), ('#38BD67', '緑系'), ('#F28C28', 'オレンジ系'), ('#832C99', '紫系'), ('#A678C9', 'ラベンダー系'), ('#A3C644', 'ライム系'), ('#2CA6A4', 'シアン系'), ('#D96C5F', 'サーモン系'), ('#858585', 'グレー系')], default='#e3f2fd', help_text='ステージカラー（タイムテーブル背景色）', max_length=7),
        ),
    ]
