# Generated by Django 5.2.7 on 2025-11-25 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('festival', '0011_alter_stage_color_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='official_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
